OBJECTS = {
    "pallet_crate": {"dims": [4, 4, 2], "stack": True},
    "tool_canister": {"dims": [2, 2, 4], "stack": True},
    "gas_cylinder": {"dims": [2, 2, 6], "stack": False},
    "drill_bit_case": {"dims": [1, 1, 4], "stack": False},
    "alignment_rod": {"dims": [1, 1, 6], "stack": False},
    "parts_bin": {"dims": [2, 1, 1], "stack": False},
    "battery_pack_a": {"dims": [4, 2, 1], "stack": False},
    "battery_pack_b": {"dims": [4, 2, 1], "stack": False},
    "cargo_panel": {"dims": [6, 4, 1], "stack": True},
    "machine_cover": {"dims": [6, 4, 2], "stack": False},
    "control_rack": {"dims": [6, 2, 1], "stack": False},
    "sensor_tray": {"dims": [4, 2, 1], "stack": False},
    "supply_case": {"dims": [4, 4, 2], "stack": False},
    "junction_box": {"dims": [2, 2, 1], "stack": False},
    "sheet_bundle_a": {"dims": [4, 4, 1], "stack": True},
    "sheet_bundle_b": {"dims": [4, 4, 1], "stack": True},
    "freight_container": {"dims": [6, 4, 2], "stack": False},
    "foam_pack": {"dims": [4, 4, 2], "stack": False},
}

OBJECT_NAMES = [
    "pallet_crate",
    "tool_canister",
    "gas_cylinder",
    "drill_bit_case",
    "alignment_rod",
    "parts_bin",
    "battery_pack_a",
    "battery_pack_b",
    "cargo_panel",
    "machine_cover",
    "control_rack",
    "sensor_tray",
    "supply_case",
    "junction_box",
    "sheet_bundle_a",
    "sheet_bundle_b",
    "freight_container",
    "foam_pack",
]
